### ISSUE TITLE
Quickfix live output

### ISSUE THREAD

**Issue by Shatur** [is0n/absp-nvim#3]
Hi! I just discovered you plugin and it looks awesome.
There is [asynctasks.vim](https://github.com/skywind3000/asynctasks.vim) and it allows to display the output directly in quickfix. It's super useful because you allows to navigate errors directly. It would be nice to implement the quickfix as a provider alongside with nvim-toggleterm.lua and Neovim's built-In terminal.

**Comment by is0n** [comment]
@Shatur, thank you for the kind words!

Could you elaborate more upon what you exactly want? Furthermore, could you explain to me what a quickfix exactly is?

**Comment by Shatur** [comment]
> Could you elaborate more upon what you exactly want? Furthermore, could you explain to me what a quickfix exactly is?

Hm... Probably it will be better you just read `:h quickfix`. In short, it is text with links to a specific buffer. So if you have compilation errors, you should be able to navigate through them.

**Comment by is0n** [comment]
Great! I'll keep you posted with any updates regarding this issue :)

**Comment by is0n** [comment]
Hey @Shatur, after a bit of research, I have found out what quickfixes are via [Vim QuickFix Lists - ThePrimeagen](https://www.youtube.com/watch?v=IoyW8XYGqjM) and I don't know if it fits in with the plugin. My plugin attempts to be a simple alternative to quickrun plugins and sublime text's build systems.

I have thought of 2 methods of implementing them into the plugin, however, as it currently stands, I won't be implementing this just yet (or possibly ever).
